# Generated by Django 2.1.5 on 2019-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='password',
            field=models.CharField(default=1111, max_length=50),
            preserve_default=False,
        ),
    ]
